[build]
  base = "frontend"
  command = "cd .. && npm install && cd frontend && npm run build"
  publish = "dist"
  functions = "../netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/health"
  to = "/.netlify/functions/api/health"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "20"
  USE_FIREBASE = "true"

